name: ShamPlugin
version: ${project.version}
website: https://modrinth.com/project/w6F3AvdX
authors: ["shamgamer"]
description: "Build Time: ${build.time}"
main: win.shamserver.Manager
api-version: 1.21
softdepend:
  - PlaceholderAPI
  - AxRewards

commands:
  sham:
    description: Root command for ShamPlugin commands
    usage: /sham <streak|uptime> ...
    aliases: []

  map:
    description: Links to the server's web world map
    usage: /map
    aliases: [servermap, worldmap]
    permission: shamplugin.map
    permission-message: You do not have permission to use this command.

  help:
    description: Shows commands players can use
    usage: /help
    aliases: [commands]
    permission: shamplugin.help
    permission-message: You do not have permission to use this command.

  streak:
    description: Shows your login streak
    usage: /streak
    permission: shamplugin.streak
    permission-message: You do not have permission to use this command.

  streaktop:
    description: Shows login streak leaderboard
    usage: /streaktop
    permission: shamplugin.streak
    permission-message: You do not have permission to use this command.

  higheststreaktop:
    description: Shows highest streak leaderboard
    usage: /higheststreaktop
    permission: shamplugin.streak
    permission-message: You do not have permission to use this command.

permissions:

  shamplugin.map:
    description: Allows usage of /map command
    default: true

  shamplugin.help:
    description: Allows usage of /help command
    default: true

  shamplugin.uptime:
    description: Allows usage of /sham uptime command
    default: true

  shamplugin.loginrewards:
    description: Allows login reward reminder message
    default: true

  shamplugin.streak:
    description: Allows usage of /streak, /sham streak, /streaktop and /higheststreaktop
    default: true

  shamplugin.admin:
    description: Admin commands
    default: op
build-time: ${build.time}