name: Kakchu
version: ${project.version}
website: https://modrinth.com/project/w6F3AvdX
authors: ["shamgamer"]
description: "Build Time: ${build.time}"
main: win.kakchuserver.Manager
api-version: 1.21
softdepend:
  - PlaceholderAPI
  - AxRewards

commands:
  map:
    description: Links to the server's web world map
    usage: /map
    aliases: [servermap, worldmap]
    permission: kakchuplugin.map
    permission-message: You do not have permission to use this command.
  help:
    description: Shows commands players can use
    usage: /help
    aliases: [commands, assistance]
    permission: kakchuplugin.help
    permission-message: You do not have permission to use this command.
  uptime:
    description: Shows server uptime statistics (day/week/month/year/all-time)
    usage: /uptime
    aliases: [servertime, kakchutime]
    permission: kakchuplugin.uptime
    permission-message: You do not have permission to use this command.

permissions:
  kakchuplugin.map:
    description: Allows usage of /map command
    default: true
  kakchuplugin.help:
    description: Allows usage of /help command
  kakchuplugin.uptime:
    description: Allows usage of /uptime command
    default: true
  kakchuplugin.loginrewards:
    description: Allows login reward reminder message
    default: true

build-time: ${build.time}